version: '3.1'
services:
  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ewm

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistic

  stats-server:
    build: ./statistic-service
    ports:
      - "9090:9090"
    environment:
      - STAT_HOST=stats-db
      - STAT_PORT=5432
      - STAT_USER=postgres
      - STAT_PASS=postgres
      - STAT_DB=statistic
    depends_on:
      - stats-db

  ewm-service:
    build: ./ewmmain-service
    ports:
      - "8080:8080"
    environment:
      - MAIN_HOST=ewm-db
      - MAIN_PORT=5432
      - MAIN_USER=postgres
      - MAIN_PASS=postgres
      - MAIN_DB=ewm
      - SERVER_IP=stats-server
      - SERVER_HOST=9090
    depends_on:
      - ewm-db
      - stats-server






