version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistic

  stats-server:
    build: ./statistic-service
    ports:
      - "9090:9090"
    environment:
      - STAT_HOST=stats-db
      - STAT_PORT=5432
      - STAT_USER=postgres
      - STAT_PASS=postgres
      - STAT_DB=statistic
    depends_on:
      - stats-db

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
